name: Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIAL }}

    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.AZURE_REGISTRY_PASSWORD }} | docker login ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }} \
          -u ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

    - name: Build and Push Docker Image to ACR
      run: |
        docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/henaapp:${{ github.sha }} .
        docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/henaapp:${{ github.sha }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: vikingfrontend # Replace with your Azure App Service name
        images: "${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/henaapp:${{ github.sha }}"
